/*! ===========================================================================
	eXe
	Copyright 2004-2005, University of Auckland
	Copyright 2004-2008 eXe Project, http://eXeLearning.org/

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
	===========================================================================

	ClozelangElement's functions by José Ramón Jiménez Reyes
	More than one right answer in the Cloze iDevice by José Miguel Andonegi
	2015. Refactored and completed by Ignacio Gros (http://www.gros.es) for http://exelearning.net/
*/
var $exe={options:{atools:{modeToggler:false,translator:false,i18n:{}}},setBodyClass:function(){var c=" js";var b=$("body");if(b.hasClass("exe-atools")&&typeof(localStorage)=='object'){var x=localStorage.getItem('exeAtoolsMode');if(x&&x=="dark")c+=" exe-atools-dm"};document.body.className+=c;},init:function(){var bod=$('body');$exe.addRoles();if(!bod.hasClass("exe-single-page")){var t=$exe.isIE();if(t){if(t>7)$exe.iDeviceToggler.init()}else $exe.iDeviceToggler.init()}
this.hasMultimediaGalleries=false;this.setMultimediaGalleries();this.setModalWindowContentSize();if(!bod.hasClass("exe-epub3")){var n=document.body.innerHTML;if(this.hasMultimediaGalleries||$(".mediaelement").length>0){$exe.loadMediaPlayer.getPlayer();}}else{bod.addClass("js");}
$exe.hint.init();$exe.setIframesProperties();$exe.hasTooltips();$exe.math.init();$exe.dl.init();$("a.exe-enlarge").each(function(i){var e=$(this);var c=$(this).children();if(c.length==1&&c.eq(0).prop("tagName")=="IMG"){e.prepend('<span class="exe-enlarge-icon"><b></b></span>');}});$exe.sfHover();$("INPUT.autocomplete-off").attr("autocomplete","off");$('.feedbackbutton.feedback-toggler').click(function(){var changeText=false;if(this.value==$exe_i18n.showFeedback||this.value==$exe_i18n.hideFeedback)changeText=true;$exe.toggleFeedback(this,changeText);});$(".textIdevice,.pblIdevice").each(function(i){$(".feedbackbutton",this).each(function(){var buttonTxt=this.value.split("|");if(buttonTxt.length==2){buttonTxt=[$.trim(buttonTxt[0]),$.trim(buttonTxt[1])]
this.value=buttonTxt[0];window['$exeTextIdeviceButtonText'+i]=buttonTxt;}
$(this).click(function(){var feedback=$(this).parent().next('.feedback');var hasCustomText=typeof(window['$exeTextIdeviceButtonText'+i])!='undefined';if(feedback.is(":visible")){if(hasCustomText)this.value=window['$exeTextIdeviceButtonText'+i][0];feedback.slideUp();}else{if(hasCustomText)this.value=window['$exeTextIdeviceButtonText'+i][1];feedback.slideDown();}
return false;});});$(".pbl-task-info",this).delay(1500).css({"opacity":0,"visibility":"visible"}).fadeTo("slow",1).each(function(){var dts=$("dt",this);var tA=$(this).css("text-align");if(tA=="right"){var width=0;dts.css("width","auto").each(function(){var w=$(this).width();if(w>width)width=w;});if(width!=0){dts.css("width",width+"px");$("dd",this).css("margin-left",width+"px");}}else if(tA=="left"){var width=0;dts.css("width","auto").each(function(){$(this).next("dd").css("margin-left",$(this).width()+"px");});}
dts.each(function(){$("span",this).attr("title",$(this).text());});});});$('.cloze-feedback-toggler').click(function(){var e=$(this);var id=e.attr('name').replace('feedback','');$exe.cloze.toggleFeedback(id,this);});$('.cloze-score-toggler').click(function(){var e=$(this);var id=e.attr('name').replace('getScore','');$exe.cloze.showScore(id,1);});$('form.cloze-form').submit(function(){var e=$(this);var id=e.attr('name').replace('cloze-form-','');try{$exe.cloze.showScore(id,1);}catch(e){var txt=$exe_i18n.dataError;if($('body').hasClass('exe-epub3'))txt+='<br /><br />'+$exe_i18n.epubJSerror;$("#clozeScore"+id).html(txt);}
return false;});$('form.quiz-test-form').submit(function(){try{calcScore2();}catch(e){var txt=$exe_i18n.dataError;if($('body').hasClass('exe-epub3'))txt+='<br /><br />'+$exe_i18n.epubJSerror;$('form.quiz-test-form input[type=submit]').hide().before(txt);}
return false;});$('.exe-radio-option').change(function(){var c=this.className.split(" ");if(c.length!=2)return;c=c[1];c=c.replace("exe-radio-option-","");c=c.split("-");if(c.length!=4)return;$exe.getFeedback(c[0],c[1],c[2],c[3]);});$('form.multi-select-form').submit(function(){return false;});$('.multi-select-feedback-toggler').click(function(){var i=this.id.replace("multi-select-feedback-toggler-","");i=i.split("-");if(i.length!=2)return;$exe.showFeedback(this,i[0],i[1]);});$('form.cloze-activity-form').submit(function(){try{var e=$(this);var id=e.attr('name').replace('cloze-form-','');$exe.cloze.submit(id);}catch(e){var txt=$exe_i18n.dataError;if($('body').hasClass('exe-epub3'))txt+='<br /><br />'+$exe_i18n.epubJSerror;if($exe.cloze.hasBeenTested==false){$exe.cloze.hasBeenTested=true;$('form.cloze-activity-form input[type=submit]').hide().before(txt);}}
return false;});if(window.DOMParser)this.clientSearch.init(bod);if($("body").hasClass("exe-atools")){var p="";if(typeof(exe_editor_mode)!="undefined")p="/scripts/exe_atools/";$exe.loadScript(p+"exe_atools.js","$exe.atools.init('"+p+"')");}},clientSearch:{init:function(bod){if(bod.hasClass("exe-web-site")&&bod.hasClass("exe-search-bar")){$.ajax({type:"GET",url:"contentv3.xml",dataType:"xml",success:function(xml){$exe.clientSearch.main=$("#main");$exe.contentv3=xml;var sF='<div id="exe-client-search">\n\t\t\t\t\t\t\t<form id="exe-client-search-form" action="#" method="GET">\n\t\t\t\t\t\t\t\t<p><label for="exe-client-search-text" class="sr-av">'+$exe_i18n.fullSearch+': </label><input type="text" id="exe-client-search-text" /> \n\t\t\t\t\t\t\t\t<input type="submit" id="exe-client-search-submit" value="'+$exe_i18n.search+'" />\n\t\t\t\t\t\t\t\t<a href="#main" id="exe-client-search-reset" title="'+$exe_i18n.hideResults+'"><span>'+$exe_i18n.hideResults+'</span></a></p>\n\t\t\t\t\t\t\t</form>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t\t<div id="exe-client-search-results"></div>';$exe.clientSearch.main.prepend(sF);$("#exe-client-search-form").submit(function(){$exe.clientSearch.search($("#exe-client-search-text").val());return false;});$("#exe-client-search-text").prop("placeholder",$exe_i18n.fullSearch+"...");$("#exe-client-search-reset").click(function(){$("#exe-client-search-text").val("")
$exe.clientSearch.search("");return false;});$exe.clientSearch.results=$("#exe-client-search-results");$exe.clientSearch.results.css("min-height",$exe.clientSearch.main.height()+"px");$("#skipNav").append(' <a href="#exe-client-search-text" id="exe-client-search-lnk" class="sr-av">'+$exe_i18n.fullSearch+'</a>');$("#exe-client-search-lnk").click(function(){$("#exe-client-search-text").focus();return false;});$("body").addClass("exe-search-bar-on");},error:function(){}});}},strip:function(html){html=html.trim();var splitter="~exe-activity-results~: ";if(html.indexOf('<div class="adivina-IDevice')==0||html.indexOf('<div class="quext-IDevice')==0||html.indexOf('<div class="rosco-IDevice')==0||html.indexOf('<div class="vquext-IDevice')==0){html=html.replace('{',splitter+'{');}else if(html.indexOf('<div class="exe-interactive-video')==0){html=splitter+html;}else if(html.indexOf('<div class="exe-sortableList')==0){html=html.replace('<ul',splitter+'<ul');}else if(html.indexOf('<u>')!=-1){html=html.replace('<u>','...'+splitter+'<u>');}
var regex=/(<([^>]+)>)/ig
html=html.replace(regex,"");html=html.replace(/</g,"&lt;");html=html.replace(/>/g,"&gt;");return html;},getNodeHTML:function(nodeNo,sTitle,query,html){query=query.toLowerCase();var div=$("<div />");div.html(html);$("instance",div).each(function(){if($(this).attr("class")=="exe.engine.node.Node"||$(this).attr("class")=="exe.engine.notaidevice.NotaIdevice"){$(this).remove();}});var res="";var currHTML;var as=$("#siteNav a");var currTit=sTitle.toLowerCase();div.find('unicode').each(function(){if($(this).attr("content")=="true"){currHTML=$(this).attr("value");if(typeof currHTML=='string')currHTML=$exe.clientSearch.strip(currHTML);if(currTit.indexOf(query)!=-1||currHTML.toLowerCase().indexOf(query)!=-1){var a=as.eq(nodeNo);a_by_title=$("#siteNav a:contains('"+sTitle+"')")
if(a.html()!=sTitle&&a_by_title){a=a_by_title;}
if(a.length==1){currHTML=currHTML.split("~exe-activity-results~: ");currHTML=currHTML[0];if(currHTML=="")currHTML="...";else res+='<li><strong><a href="'+a.attr("href")+'" \n\t\t\t\t\t\t\tclass="exe-client-search-result-link">'+sTitle+'</a> &rarr; </strong>\n\t\t\t\t\t\t\t<span class="exe-client-search-result-detail">'+currHTML+"</span></li>";}}}});return res;},splitByWords:function(text,startFrom,lengthFrom){var len=text.length,re=/[ ,.]/,fr=(startFrom<=0)?0:text.substr(startFrom).search(re)+startFrom+1,to=(lengthFrom>=len)?len:text.substr(lengthFrom).search(re)+lengthFrom;if(fr===-1)fr=0;if(to===(lengthFrom-1))to=len;return text.substr(fr,to);},search:function(query){if(query.length<3){$("body").removeClass("exe-client-search-results");return;}
var xml=$exe.contentv3;var nodeNo=0;$("body").addClass("exe-client-search-results");$exe.clientSearch.results.html("");var results="";$(xml).find('instance').each(function(){if($(this).attr("class")=="exe.engine.node.Node"){var currentNode=$(this);var sTitle=currentNode.find('unicode').eq(0).attr("value");var str="";try{str=currentNode.html();}catch(e){var s=new XMLSerializer();var d=this;str=s.serializeToString(d);var tmp=$("<div></div>");tmp.html(str);var html=$("instance",tmp).eq(0).html();str=html;}
results+=$exe.clientSearch.getNodeHTML(nodeNo,sTitle,query,str.replace(/script/g,"script_"));nodeNo++;}});if(results!=""){results='<p>'+$exe_i18n.searchResults.replace("%","<strong>"+query+"</strong>")+':</p><ul>'+results+'</ul>';$exe.clientSearch.results.html(results);$(".exe-client-search-result-link",$exe.clientSearch.results).html(function(_,html){html=html.replace(/script_/g,"script");var re=new RegExp('('+query+')','gi');return html.replace(re,'<mark class="exe-client-search-result">$1</mark>');});$(".exe-client-search-result-detail",$exe.clientSearch.results).each(function(i){var max=200;var c=$(this).text();c=$exe.clientSearch.strip(c);var n="";if(c.length>(max+100)){var start=$exe.clientSearch.splitByWords(c,0,max);var end=c.replace(start," ");n+=start;n+='<a href="#exe-client-search-text-'+i+'" title="'+$exe_i18n.more+'" class="exe-client-search-read-more">[&hellip;]</a>';n+='<span class="js-hidden" id="exe-client-search-text-'+i+'">';n+=end;n+='</span>';this.innerHTML=n;}